apiVersion: v1
kind: Service
metadata:
  name: java-app-lb
spec:
  ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
  selector:
    app: java-app
  type: LoadBalancer
status:
  loadBalancer: {}
    
